version: "3.9"

services:
  ts-network:
    image: tailscale/tailscale:latest
    hostname: nextcloud
    environment:
      - TS_AUTHKEY=tskey-auth-kWazaxnWBV11CNTRL-WRfZW2PdcxRqXkLbRjv7xRs6YE45PpFK
      - TS_SERVE_CONFIG=/config/nextcloud.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./config:/config
      - tailscale-data-nextcloud:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  db:
    image: mariadb:11.4
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass 1234560987Isco@
    environment:
      - REDIS_PASSWORD=1234560987Isco@
  app:
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST_PASSWORD=1234560987Isco@
    env_file:
      - db.env
    depends_on:
      - db
      - redis
      - ts-network
    network_mode: service:ts-network

volumes:
  tailscale-data-nextcloud:
    driver: local
  db:
    external: true
  nextcloud:
    external: true
